### PR TITLE
changed parameter in SequenceDescription from ImgLoader to BasicImgLo…

### PR DESCRIPTION
**Pull request by axtimwalde**
…ader

to make it possibel to feed into

mpicbg.spim.data.sequence.SequenceDescription.setImgLoader(L extends BasicImgLoader)

### CODE REVIEW

**Comment by axtimwalde** [comment]
Any objections?

**Comment by StephanPreibisch** [comment]
No objections :) @tpietzsch?

**Comment by tpietzsch** [comment]
@StephanPreibisch  if anybody should have objections this would be you... This will break SPIM_Registration, I think. [ImgLoader](https://github.com/bigdataviewer/spimdata/blob/master/src/main/java/mpicbg/spim/data/sequence/ImgLoader.java) (via [SetupImgLoader] (https://github.com/bigdataviewer/spimdata/blob/master/src/main/java/mpicbg/spim/data/sequence/SetupImgLoader.java)) provides the `getImageSize()` and `getVoxelSize()` methods that you rely on. This is why `SequenceDescription` exists in the first place!

@axtimwalde Looks like we cannot do this. What do you need it for? For BDV, there is [SequenceDescriptionMinimal] (https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/spimdata/SequenceDescriptionMinimal.java) which already has what you want. Is there any reason that you cannot use either that or `AbstractSequenceDescription` in your code?

The idea for the spimdata design is that AbstractSequenceDescription can be extended in different ways while still maintaining file format compatibility. That way, BDV can read (via [XmlIoSpimDataMinimal] (https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/spimdata/XmlIoSpimDataMinimal.java)) an XML file that was written by SPIM_Registration as a full `SequenceDescription` (via [XmlIoSequenceDescription] (https://github.com/bigdataviewer/spimdata/blob/master/src/main/java/mpicbg/spim/data/sequence/XmlIoSequenceDescription.java)) and just ignores (but retains) additional stuff put in there by SPIM_Registration or whoever else puts their own extension in the XML. So, `AbstractSpimData` is the abstract base class `SpimDataMinimal` is the minimal instantiation with no extensions whatsoever, `SpimData` is the SPIM_Registration thing (although I think @StephanPreibisch does another extension `SpimData2` on that).

@axtimwalde It is perhaps unfortunate that [SequenceDescriptionMinimal] (https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/spimdata/SequenceDescriptionMinimal.java) lives in the bigdataviewer-core repository. We could move it to spim_data to have it all in one place?

**Comment by tpietzsch** [comment]
@axtimwalde one more comment: It would be great if as far as possible you could stick to `AbstractSpimData` for stuff that doesn't need format extensions. For example, `BigDataViewer.open()` variants take `AbstractSpimData` and can therefore be used both with the `SpimDataMinimal` that the BDV reads from XML, and also with `SpimData(2)` when called from SPIM_Registration as a visualisation front-end.

**Comment by StephanPreibisch** [comment]
Hi @tpietzsch, you are right, it was late yesterday :( We should not do that, it makes no sense really. I forgot that the BasicImgLoader does not have that information and that you just use the registration - because I did not really look too much into your refactoring and the SetupImgLoader class.

At the end this was all trigged by by Burkhard trying to update the KLB reader, I understand the problem now I think, I will talk to him.

I think the core problem is to - as you pointed out @tpietzsch - use the AbstractSequenceDescription, not the implementation of it (SpimDataMinimal).

Thanks so much for showing me my stupidness :)
Stephan

**Comment by tpietzsch** [comment]
@StephanPreibisch LOL :) always a pleasure...

**Comment by tpietzsch** [comment]
if I can help with the KLB reader let me know

**Comment by axtimwalde** [comment]
@tpietzsch and @StephanPreibisch , thanks for clarifying and the offer to help.  I admit that I am completely ignorant about all that SPIM stuff.  Burkhard came to my office yesterday and showed me that his KLB reader was broken since the last BDV update, so we tried to get it to at least compile, not getting a deep understanding of the many ImgLoaders, SequenceDescriptions, Abstract, and Basic veriations thereof.  KLB's javaWrapper is here:

https://bitbucket.org/fernandoamat/keller-lab-block-filetype/src/4c90419083ab268b8f2cfc3f658ed3c7c690606c/javaWrapper/?at=master

Thanks and sorry for the noise.

**Comment by tpietzsch** [comment]
I'll look into KLB wrapper

**Pull request closed without merging**
